# RT-Thread building script for component

Import('rtconfig')
Import('RTT_ROOT')
from building import *

cwd = GetCurrentDir()
src = ['drivers/uart.c',
	'drivers/can.c',
	'drivers/vga.c']

CPPPATH = [ cwd + '/drivers', cwd + '/env', cwd + '/include',
            cwd + '/include/devices']

CPPDEFINES = []

group = DefineGroup('Libraries', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES=CPPDEFINES)

Return('group')
