Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = os.path.join(str(Dir('#')))

# add the general drvers.
src = Glob("*.c")

CPPPATH = [cwd + '/drivers', cwd + '/platform/include/devices']

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
